### ISSUE TITLE
回答问题变更用户组

### ISSUE THREAD

**Issue by MiracleYF** [MiracleYF/jikipedia#112]
通过回答随机问题，将用户组变更：guest -》 editor

**Comment by MiracleYF** [comment]
- 加载问题，return 问题
- 提交问题，发送问题+答案
- 【后台】回答列表，需要显示问题、答案、回答人名称
- 【后台】审核通过/拒绝+相应理由，然后进行消息盒子通知

**Comment by xy6321** [comment]
1、
/wiki/get_question
Token only
return "question"
2、
/wiki/commit_answer
Token, question, answer
return 200
3、
/admin/get_answer_list
Token only
return: { id, name, question, answer, created_at, status}
4、
/admin/process_answer
Token, id, status, reply
return 200
