### ISSUE TITLE
后台改进

### ISSUE THREAD

**Issue by MiracleYF** [MiracleYF/jikipedia#159]
- 发通知/个人，群体
- 给用户打钱
- 后台审核词条，标注新建，还是编辑
- 小号机器人标注已有词条数量
- 审核词条时，如果编辑，显示该词条上一个状态

**Comment by MiracleYF** [comment]
你画我猜钱进钱包，不直接打款

**Comment by huntrist** [comment]
- 举报有可能有用户没有名字。。。能不能让没有名字的也显示用户ID？
- 后台发PUSH
