### ISSUE TITLE
BUGs for XY

### ISSUE THREAD

**Issue by MiracleYF** [MiracleYF/jikipedia#162]
【DONE】1. 已经pass的词，后台再改processing状态会出bug
【DONE】2. 你画我猜formid 有问题 => 没问题，好像WX就这么设计的
【DONE】3. 金蛋活动结束后，别返回403，否则会卡住
【DONE】4. x元提现上线，人工一次后，重置x上限
5. 举报后，可以不发站内信

**Comment by huntrist** [comment]
成为编辑 成就 已经成为编辑的人无法获得

**Comment by xy6321** [comment]
已解决。
