### ISSUE TITLE
消息盒子/站内信

### ISSUE THREAD

**Issue by huntrist** [MiracleYF/jikipedia#21]
内部通知渠道

**Comment by xy6321** [comment]
目前基于微信“服务通知”的“模板消息”。
用户每触发一次，七天之内对于该触发，最多可回复一条消息。
发送消息的API已完成测试。
客户端所有有可能需要回复消息的地方均需更改成表单提交的形式（创建/编辑词条、举报，其他情况暂未想到），同时需要将获取到的form_id一并传入数据库。
已有的词条、举报因无form_id无法回复。
若自己创建站内信的形式，内容不再受模板限制，但没有推送。是否还需要站内信？

**Comment by MiracleYF** [comment]
- 获取消息列表api
url:/getMessageList
token
return: [{id:id,title:title,content:content,time:time,readFlag:true/false}]
time格式：2017/05/07

**Comment by MiracleYF** [comment]
时间格式，需要把“-”换成“/”
