### ISSUE TITLE
修改/创建词条页面添加Tags使用流程有问题

### ISSUE THREAD

**Issue by huntrist** [MiracleYF/jikipedia#47]
搜索一个Tag，如果该Tag不存在，点击搜索框下的 添加“XX"为Tag后，没有任何直观反映，但是Tag实际上已经被添加上了。再次点击也没有提示说已经添加。并且该Tag并不会变成如 已有 Tag那样可以再次点击取消。
-》统一已有和新tag创建为统一界面（点击一次添加，再次点击取消）-》用户无需知道Tag是否是新建的？

**Comment by MiracleYF** [comment]
see #64
