### ISSUE TITLE
有些页面不应该允许分享或实际分享页面应该为主页

### ISSUE THREAD

**Issue by huntrist** [MiracleYF/jikipedia#52]
比如说 在 我的 页面分享，应该实际分享页面是主页？搜索页面不应该能分享？（系统自带分享/button分享）

**Comment by MiracleYF** [comment]
右上角，系统转发，带有title（黑色字，小鸡百科）
自定义button转发，没有title

**Comment by MiracleYF** [comment]
分享页仅保留index/singleTerm
分享时，全部带有黑色标题，标题为词条title
