### ISSUE TITLE
姓名里有表情符号识别异常

### ISSUE THREAD

**Issue by xy6321** [MiracleYF/jikipedia#61]
如题，改名字若有表情符号大概率提示昵称已存在

**Comment by xy6321** [comment]
全库已更改为utf8mb4编码，可正确记录emoji。
若需要正确搜索出不同emoji，需要在条件添加 BINARY 字段（例：WHERE BINARY `name` = ?），此做法同时会造成搜索结果，区分英文字母大小写。

**Comment by MiracleYF** [comment]
future improvement needed

**Comment by xy6321** [comment]
换了utf8mb4_unicode_520_ci排序，终于tmd彻底解决了。
以后再碰类似无法区分的问题，可优先尝试高于520的排序方式。
但是很大概率需要升级mysql版本了。
